version: '3.8'
services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    expose:
      - "5252"
    container_name: softy-pinko-back-end

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    expose:
      - "9000"
    container_name: softy-pinko-front-end
    depends_on:
      - back-end

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy
    ports:
      - "80:80"
    depends_on:
      - back-end
      - front-end
    container_name: proxy

